### ISSUE TITLE
Error: Couldn't get items from config file.

### ISSUE THREAD

**Issue by ExtinctAxolotl** [Misterio77/flavours#36]
Hey there!
First off, thank you for developing this, it looks incredibly promising! :+1:
I just can't seem to get it to work, whenever I run `flavours apply <theme-name>` (`nord` for example) I just get the following error message:
```
Error: Couldn't get items from config file. Check the default file or github for config examples.
```

This is my configuration:
```toml
# Commands go through bash
shell = "bash -c '{}'"

# Sway supports the default '#' comments, so it can be ommited
# 'rewrite' is also ommited, as it defaults to false
[[items]]
file = "~/.config/kitty/colors.conf"
subtemplate = "default"
template = "kitty"
```

And I ran `flavours update all` several times now.

Have a good day!
