### ISSUE TITLE
hook not working with emacs

### ISSUE THREAD

**Issue by auralluring** [Misterio77/flavours#86]
i feel like i must be doing something wrong here, but i can't figure out what. i have a custom template i made that injects itself into an [autothemer](https://github.com/jasonm23/autothemer) theme file. that part works perfectly, and emacs has no issues with the generated theme. 

the problem is that the hook just... isn't working. here's its whole section in the `config.toml` file:

```toml
[[items]]
file = "~/.config/emacs/flavours-theme.el"
template = "emacs"
subtemplate = "custom"
start = ";; Start Flavours"
end = ";; End Flavours"
hook = "emacsclient -e '(my/load-theme)'"
``` 

i was having some minor problems with the emacs daemon having trouble starting yesterday, but it seems fine now. the thing that's tripping me up about this is that the same exact command works fine when i execute it manually in a terminal. and if i put a different command there - for example, to open a new terminal - it too does its job! i've also tried changing the shell to bash and even zsh - nothing.

i used to use pywal/wgptk, with a wrapper to execute a custom script afterwards. the same command was in there (i actually created the function for that purpose) and i had no problems with it, so i really don't get what's going wrong here.
